GRANT USAGE ON SCHEMA flashmsg TO "ode-app";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA flashmsg TO "ode-app";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA flashmsg TO "ode-app";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA flashmsg TO "ode-app";