GRANT USAGE ON SCHEMA conversation TO "ode-app";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA conversation TO "ode-app";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA conversation TO "ode-app";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA conversation TO "ode-app";